{% set version = '1.1-9.4' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-suppdists
  version: {{ version|replace("-", "_") }}

source:
  fn: SuppDists_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/SuppDists_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/SuppDists/SuppDists_{{ version }}.tar.gz
  sha256: fcb571150af66b95dcf0627298c54f7813671d60521a00ed157f63fc2247ddb9

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base

  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('SuppDists')"           # [not win]
    - "\"%R%\" -e \"library('SuppDists')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: no longer valid
  license: GPL (>= 2)
  summary: Ten distributions supplementing those built into R. Inverse Gauss, Kruskal-Wallis,
    Kendall's Tau, Friedman's chi squared, Spearman's rho, maximum F ratio, the Pearson
    product moment correlation coefficient, Johnson distributions, normal scores and
    generalized hypergeometric distributions. In addition two random number generators
    of George Marsaglia are included.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\lib\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - qwhelan
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: SuppDists
# Version: 1.1-9.4
# Date: 2009-12-09
# Title: Supplementary Distributions
# Author: Bob Wheeler <bwheelerg@gmail.com>
# Maintainer: ORPHANED
# Description: Ten distributions supplementing those built into R. Inverse Gauss, Kruskal-Wallis, Kendall's Tau, Friedman's chi squared, Spearman's rho, maximum F ratio, the Pearson product moment correlation coefficient, Johnson distributions, normal scores and generalized hypergeometric distributions. In addition two random number generators of George Marsaglia are included.
# License: GPL (>= 2)
# URL: no longer valid
# Depends: R (>= 3.3.0)
# NeedsCompilation: yes
# Packaged: 2016-09-19 09:56:39 UTC; ripley
# X-CRAN-Comment: Orphaned on 2013-03-22: the maintainer is unresponsive.
# Repository: CRAN
# Date/Publication: 2016-09-23 09:21:14

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
