travis:
  secure:
    BINSTAR_TOKEN: P3Ej3qYVuLV+/U4rpYLbXlQ276C4zEgj0P0+483XgY5KoqaQBYwTT/853h5ZC+oIWmaYLOiCnqscDRLOEqmQm12wWbxO6RlNScmLTz6rgo+zP5cU7wJDHMk223PQbEJ8/daRrVN6hNL/fKB795H1bffcji1sdrYTaREvUOLN19oz1TvTBHvf6gctkVyQTYOQyuCLHf/aArjwzBB0R2P/viwi6DAU8O21cean6s2YiznxOcHtcml6j565/slPxAxFBL73A+eaqGr8Cdt5NoKTLGvQh4kV/Puv5AQuhxF5ZdM9JKZOhtVQTG8Qt1sxgQyjEoseM2L6uQqMYiNI2W8ZjM44UNDPkMOlMpbWrmQ978lAmA4I5c/HsJb7J9xs97u5AUPZOQDwxMiodBwk7vNG5mLzYXDnKzkA8EfnknV0pRv0dlOI1Io3luXKTnLcjOkv+QLui68dfILLACOTVdx+5uUvEFrhMfkt5M6LjxInCoT7vByGHV2lBYRxFJQg5ebbuN+qjAfjjieJtlbokSVnc8d5jXo7v16uMZJQZ2azILRH6DhMJYPP55w+0m3BzJa7hds/XVUDczqVLiZFbbmgP2wYpkr181qbFWHevZmbwhZnvHzHAoLcJmkLSyAiwGjbYzrTzF+2ud6fMfEUU1lDT6oPllZSiMjPr+6LmQ5ym7U=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
