travis:
  secure:
    BINSTAR_TOKEN: ObYLKfm6dYm6IwJW0Pt5kydpt6J9lGREaSBBvYMgN+1CufHgeTSJ7mH4t8vsE7unjOQ2JI7NwZ+CImkTPXAh2Mk/I8NBrn0JzRmODYGyuVN0YxX4GNboVV0+le3cjnsyy9ix5Hr+iB+tTEeRyOckzZzY4NJ0Idmo+NqFynwyFch7cBifXsqQ++ME/wqLGf1+HBd7+L8G+P/L8mdEVDFUCHjlhrncHcHlZhnyXzJaLnY6yF11p8c2MMlvPobldnCVhHjDrn7sf1Qg3YNC4lYD/OlCcC2GKaGU8fUnQe2e1rHKG5DFTbEECugSJ6bT+Z+Iu7IJx9D75xf174b6NTbeKJAxR/mePe0sRfu9PZbWFQeozd+iMf3zA8XnzfeywFTN/UKVfcGCpvENhdyTQgaNkrSDqRmkQ7vj7wzeUW9nezQbn/kR+JUEDckboEf/3Pp9A35Ww0ivxVCEopPDx6Q5HJ7aJfKlsn0ZULYg561vkB6BH8LimVS1mJS4nkAzbOSKeoNTUnZCDTVoAxhA3i67Y5glHwknMeie39W9EBAW4lHSSDZELbuEPbnIcdT/dYbHwy1GZ8s6rQg5mwP9el9RtShi8Ff1SMVE2pnQ0k/kQMwZnl7lfd1albANpI8YiUSrhVwQDK1hqbEdRxecGYwh4jNdzie/WTKYUHpE6bjSazU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
